//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.22 at 07:19:36 PM CET 
//


package com.hkeya.xml.train;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hkeya.xml.train package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hkeya.xml.train
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrainDetailsResponse }
     * 
     */
    public TrainDetailsResponse createTrainDetailsResponse() {
        return new TrainDetailsResponse();
    }

    /**
     * Create an instance of {@link Train }
     * 
     */
    public Train createTrain() {
        return new Train();
    }

    /**
     * Create an instance of {@link TrainDetailsRequest }
     * 
     */
    public TrainDetailsRequest createTrainDetailsRequest() {
        return new TrainDetailsRequest();
    }

    /**
     * Create an instance of {@link AddTrainRequest }
     * 
     */
    public AddTrainRequest createAddTrainRequest() {
        return new AddTrainRequest();
    }

}
