//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.22 at 07:19:36 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hkeya.com/xml/train", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hkeya.xml.train;
