//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.22 at 07:19:36 PM CET 
//


package com.hkeya.xml.train;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Train complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Train">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="villeDep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="villeArriv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jourDep" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="intervalleTemps" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Train", propOrder = {
    "id",
    "villeDep",
    "villeArriv",
    "jourDep",
    "intervalleTemps"
})
public class Train {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String villeDep;
    @XmlElement(required = true)
    protected String villeArriv;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar jourDep;
    @XmlElement(required = true)
    protected BigInteger intervalleTemps;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the villeDep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVilleDep() {
        return villeDep;
    }

    /**
     * Sets the value of the villeDep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVilleDep(String value) {
        this.villeDep = value;
    }

    /**
     * Gets the value of the villeArriv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVilleArriv() {
        return villeArriv;
    }

    /**
     * Sets the value of the villeArriv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVilleArriv(String value) {
        this.villeArriv = value;
    }

    /**
     * Gets the value of the jourDep property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getJourDep() {
        return jourDep;
    }

    /**
     * Sets the value of the jourDep property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setJourDep(XMLGregorianCalendar value) {
        this.jourDep = value;
    }

    /**
     * Gets the value of the intervalleTemps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntervalleTemps() {
        return intervalleTemps;
    }

    /**
     * Sets the value of the intervalleTemps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntervalleTemps(BigInteger value) {
        this.intervalleTemps = value;
    }

}
