//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.23 at 07:04:22 PM CET 
//


package com.reseration.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reseration.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reseration.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrainIdResponse }
     * 
     */
    public TrainIdResponse createTrainIdResponse() {
        return new TrainIdResponse();
    }

    /**
     * Create an instance of {@link AddReservationRequest }
     * 
     */
    public AddReservationRequest createAddReservationRequest() {
        return new AddReservationRequest();
    }

    /**
     * Create an instance of {@link ReservationsRequest }
     * 
     */
    public ReservationsRequest createReservationsRequest() {
        return new ReservationsRequest();
    }

    /**
     * Create an instance of {@link ReservationDetailsResponse }
     * 
     */
    public ReservationDetailsResponse createReservationDetailsResponse() {
        return new ReservationDetailsResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link SearchedTrainRequest }
     * 
     */
    public SearchedTrainRequest createSearchedTrainRequest() {
        return new SearchedTrainRequest();
    }

    /**
     * Create an instance of {@link RemoveReservationRequest }
     * 
     */
    public RemoveReservationRequest createRemoveReservationRequest() {
        return new RemoveReservationRequest();
    }

    /**
     * Create an instance of {@link ClientsRequest }
     * 
     */
    public ClientsRequest createClientsRequest() {
        return new ClientsRequest();
    }

    /**
     * Create an instance of {@link UpdateTrainRequest }
     * 
     */
    public UpdateTrainRequest createUpdateTrainRequest() {
        return new UpdateTrainRequest();
    }

    /**
     * Create an instance of {@link RemoveTrainRequest }
     * 
     */
    public RemoveTrainRequest createRemoveTrainRequest() {
        return new RemoveTrainRequest();
    }

    /**
     * Create an instance of {@link TrainDetailsResponse }
     * 
     */
    public TrainDetailsResponse createTrainDetailsResponse() {
        return new TrainDetailsResponse();
    }

    /**
     * Create an instance of {@link Train }
     * 
     */
    public Train createTrain() {
        return new Train();
    }

    /**
     * Create an instance of {@link RemoveClientRequest }
     * 
     */
    public RemoveClientRequest createRemoveClientRequest() {
        return new RemoveClientRequest();
    }

    /**
     * Create an instance of {@link ReservationIdResponse }
     * 
     */
    public ReservationIdResponse createReservationIdResponse() {
        return new ReservationIdResponse();
    }

    /**
     * Create an instance of {@link TrainsRequest }
     * 
     */
    public TrainsRequest createTrainsRequest() {
        return new TrainsRequest();
    }

    /**
     * Create an instance of {@link UpdateReservationRequest }
     * 
     */
    public UpdateReservationRequest createUpdateReservationRequest() {
        return new UpdateReservationRequest();
    }

    /**
     * Create an instance of {@link UpdateClientRequest }
     * 
     */
    public UpdateClientRequest createUpdateClientRequest() {
        return new UpdateClientRequest();
    }

    /**
     * Create an instance of {@link ClientIdResponse }
     * 
     */
    public ClientIdResponse createClientIdResponse() {
        return new ClientIdResponse();
    }

    /**
     * Create an instance of {@link ClientDetailsResponse }
     * 
     */
    public ClientDetailsResponse createClientDetailsResponse() {
        return new ClientDetailsResponse();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link AddTrainRequest }
     * 
     */
    public AddTrainRequest createAddTrainRequest() {
        return new AddTrainRequest();
    }

    /**
     * Create an instance of {@link AddClientRequest }
     * 
     */
    public AddClientRequest createAddClientRequest() {
        return new AddClientRequest();
    }

    /**
     * Create an instance of {@link Trains }
     * 
     */
    public Trains createTrains() {
        return new Trains();
    }

    /**
     * Create an instance of {@link Reservations }
     * 
     */
    public Reservations createReservations() {
        return new Reservations();
    }

    /**
     * Create an instance of {@link TrainReservation }
     * 
     */
    public TrainReservation createTrainReservation() {
        return new TrainReservation();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

}
