//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.23 at 07:04:22 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.reseration.com/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.reseration.xml;
