//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.23 at 07:04:22 PM CET 
//


package com.reseration.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Trains complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trains">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="V_depart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="V_arrive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="capacite" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nbr_place_actuel" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trains", propOrder = {
    "id",
    "vDepart",
    "vArrive",
    "capacite",
    "nbrPlaceActuel"
})
public class Trains {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(name = "V_depart", required = true)
    protected String vDepart;
    @XmlElement(name = "V_arrive", required = true)
    protected String vArrive;
    @XmlElement(required = true)
    protected BigInteger capacite;
    @XmlElement(name = "nbr_place_actuel", required = true)
    protected BigInteger nbrPlaceActuel;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the vDepart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVDepart() {
        return vDepart;
    }

    /**
     * Sets the value of the vDepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVDepart(String value) {
        this.vDepart = value;
    }

    /**
     * Gets the value of the vArrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVArrive() {
        return vArrive;
    }

    /**
     * Sets the value of the vArrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVArrive(String value) {
        this.vArrive = value;
    }

    /**
     * Gets the value of the capacite property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapacite() {
        return capacite;
    }

    /**
     * Sets the value of the capacite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapacite(BigInteger value) {
        this.capacite = value;
    }

    /**
     * Gets the value of the nbrPlaceActuel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNbrPlaceActuel() {
        return nbrPlaceActuel;
    }

    /**
     * Sets the value of the nbrPlaceActuel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNbrPlaceActuel(BigInteger value) {
        this.nbrPlaceActuel = value;
    }

}
